version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - trc_network

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - trc_network

  kafka-consumer:
    image: kafka-consumer
    container_name: kafka-consumer
    build:
      context: ./containers/kafka-consumer/
    volumes:
      - ./:/opt/sde
    networks:
      - trc_network
  
  jupyter-lab:
    image: jupyter/datascience-notebook
    container_name: jupyter-lab
    ports: 
      - "8888:8888"
    networks:
      - trc_network

# docker run                  \
# --rm -p 8888:8888           \
# -e JUPYTER_ENABLE_LAB=yes   \
# -v "$PWD":/home/jovyan/work \
# jupyter/datascience-notebook

networks:
  trc_network:
    name: trc_network
